version: '3.8'

services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET=supersecreta-chave-256bits
    networks:
      - ecommerce-net

  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - ecommerce-net

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - auth-service
      - catalog-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET=supersecreta-chave-256bits
      - AUTH_URL=http://auth-service:8081
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge
